quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ticketing
quarkus.datasource.password=ticketing_secret
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/ticketing
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true